/* Lecture video catalogue (generated once from an old page by tools/lecture-videos-to-js.mjs). Ages are as shown on the playlist on 29 September 2026. */
const STUDY = {
 "intro": {
  "title": "Introduction",
  "id": "7kNHWAwDO1w",
  "note": "Course introduction, uploaded about 6 years ago"
 },
 "units": [
  { "n": 1, "topic": "Arguments", "groups": [ { "kind": "lecture", "title": "Lectures", "age": "about 6 years ago", "items": [ { "no": "1", "title": "Arguments and Validity", "id": "Gvd6ziVtLG0", "label": "Lecture 1" }, { "no": "2", "title": "Tricky Arguments and Soundness", "id": "X4sflV8wQeo", "label": "Lecture 2" } ] } ]
  },
  { "n": 2, "topic": "Sentential semantics", "groups": [ { "kind": "lecture", "title": "Lectures", "age": "about 6 years ago", "items": [ { "no": "1", "title": "Syntax and Official Notation", "id": "sn8Z2fomV3k", "label": "Lecture 1" }, { "no": "2", "title": "Informal Notation and Main Connectives", "id": "2iTh4IL1ahk", "label": "Lecture 2" }, { "no": "3", "title": "Truth-Tables", "id": "OhKZScBoCVM", "label": "Lecture 3" }, { "no": "4", "title": "Semantic Properties", "id": "bG_Xdxgkq9k", "label": "Lecture 4" }, { "no": "5", "title": "Shortened Truth-Tables", "id": "yXonziydeqY", "label": "Lecture 5" }, { "no": "6", "title": "Wrap-up", "id": "Z_MKlP4_Z0E", "label": "Lecture 6" } ] }, { "kind": "l2010", "title": "Logic 2010 demos", "age": "about 9 years ago", "items": [ { "no": "7", "title": "Parsing", "id": "9oMJIv1sPGQ", "label": "Logic 2010" }, { "no": "8", "title": "Truth Tables", "id": "JYD8rNmbsrE", "label": "Logic 2010" } ] }, { "kind": "example", "title": "Example problems", "age": "6–10 years ago", "items": [ { "no": "9", "title": "Full Truth Tables", "id": "dnxRazaOegM", "label": "Example" }, { "no": "10", "title": "Full Truth Table 2", "id": "zCHy9Gp7vdQ", "label": "Example" }, { "no": "11", "title": "Notation", "id": "WKuSEzkAi5w", "label": "Example" }, { "no": "12", "title": "Shortened Truth Table", "id": "XWmzOojVvcs", "label": "Example" }, { "no": "13", "title": "Shortened Truth Table 1", "id": "hxv8FoAvByQ", "label": "Example" }, { "no": "14", "title": "Shortened Truth Table 2", "id": "djMM2lpg1q0", "label": "Example" } ] } ]
  },
  { "n": 3, "topic": "Sentential symbolization", "groups": [ { "kind": "lecture", "title": "Lectures", "age": "about 3 years ago", "items": [ { "no": "1", "title": "The Five Logical Connectives", "id": "aKS7uJIdmtQ", "label": "Lecture 1" }, { "no": "2", "title": "Stylistic Variants", "id": "ULnySRIpL3Q", "label": "Lecture 2" }, { "no": "3", "title": "Only and Three Common Phrases", "id": "T7J2d16Fjm0", "label": "Lecture 3" }, { "no": "4", "title": "Logical Equivalencies and Symbolization Strategies", "id": "Ih_zH2_AWVc", "label": "Lecture 4" }, { "no": "5", "title": "Quantities and Translations", "id": "lLQrr_lYtA8", "label": "Lecture 5" }, { "no": "6", "title": "Ambiguous, Non-Restrictive, and Reference Phrases", "id": "JQMmfGokL5g", "label": "Lecture 6" }, { "no": "7", "title": "Wrap-Up", "id": "SCTZzIg7tk0", "label": "Lecture 7" } ] }, { "kind": "l2010", "title": "Logic 2010 demos", "age": "about 10 years ago", "items": [ { "no": "8", "title": "Symbolization", "id": "A7-LymFITdU", "label": "Logic 2010" } ] }, { "kind": "example", "title": "Example problems", "age": "6–10 years ago", "items": [ { "no": "9", "title": "Basic Symbolization", "id": "WJ9ih54ia2I", "label": "Example" }, { "no": "10", "title": "Five Questions a", "id": "LoPBhlhlARc", "label": "Example" }, { "no": "11", "title": "Five Questions b", "id": "KGuO3cBFBsw", "label": "Example" }, { "no": "12", "title": "Test Question Examples", "id": "60QPd5TSqvg", "label": "Example" }, { "no": "13", "title": "Three Harder Questions a", "id": "1ofC-lxFOO0", "label": "Example" }, { "no": "14", "title": "Three Harder Questions b", "id": "auPi_iWb9t8", "label": "Example" } ] } ]
  },
  { "n": 4, "topic": "Sentential derivations", "groups": [ { "kind": "lecture", "title": "Lectures", "age": "9–10 years ago", "items": [ { "no": "1", "title": "Derivations in SL, part 1", "id": "6OoV1YyMP-Y", "label": "Lecture" }, { "no": "2", "title": "Derivations in SL, part 2", "id": "BlngZYYyD08", "label": "Lecture" }, { "no": "3", "title": "Derivations in SL, part 3", "id": "00HLGCZdYiQ", "label": "Lecture" } ] }, { "kind": "skill", "title": "Skills", "age": "about 5 years ago", "items": [ { "no": "4", "title": "Show Line Breakdown", "id": "JTTxkwK_mLk", "label": "Skill 1" }, { "no": "5", "title": "Proof Structure", "id": "mW8BkxDLIhI", "label": "Skill 2" }, { "no": "6", "title": "Contradiction Generators", "id": "Ru-q3WycDro", "label": "Skill 3" }, { "no": "7", "title": "Show Something Nice", "id": "8h2bL2RKcqI", "label": "Skill 4" } ] }, { "kind": "l2010", "title": "Logic 2010 demos", "age": "about 10 years ago", "items": [ { "no": "8", "title": "Derivation", "id": "HDmCo9bbWpA", "label": "Logic 2010" } ] }, { "kind": "example", "title": "Example problems", "age": "5–10 years ago", "items": [ { "no": "9", "title": "All Rules 1", "id": "k0fK1nfJ3Sk", "label": "Example" }, { "no": "10", "title": "All Rules 2", "id": "GwdkzuCLgjo", "label": "Example" }, { "no": "11", "title": "All Rules 3", "id": "Y1I_O48XGdM", "label": "Example" }, { "no": "12", "title": "Conditional Derivation", "id": "Qbwm-p78q54", "label": "Example" }, { "no": "13", "title": "Direct Derivation", "id": "UvNOZhH0p2Q", "label": "Example" }, { "no": "14", "title": "Harder Basic Rules", "id": "MD3rNgsj_qE", "label": "Example" }, { "no": "15", "title": "Harder Basic Rules 2", "id": "vAZRacu3RIA", "label": "Example" }, { "no": "16", "title": "Indirect Derivation", "id": "NI1ZHlvxidk", "label": "Example" }, { "no": "17", "title": "Theorem 1 Biconditional", "id": "cAKT6inHKUg", "label": "Example" }, { "no": "18", "title": "Theorem 2", "id": "93iVmELn4yY", "label": "Example" } ] } ]
  },
  { "n": 5, "topic": "Single-place predicate symbolization", "groups": [ { "kind": "lecture", "title": "Lectures", "age": "about 3 years ago", "items": [ { "no": "1", "title": "Introduction to Predicate Logic", "id": "KuCaWy3xs-M", "label": "Lecture 0" }, { "no": "2", "title": "Names, Predicates, and Quantifiers", "id": "6k5HZo-IRyU", "label": "Lecture 1" }, { "no": "3", "title": "Syntax and Scope", "id": "k8h-dH5hkVw", "label": "Lecture 2" }, { "no": "4", "title": "Quantifiers and Canonical Form", "id": "qf5wlbJzFCM", "label": "Lecture 3" }, { "no": "5", "title": "Complex Clauses", "id": "WVjEind2LZs", "label": "Lecture 4", "note": "Uploaded twice. The link above is the one with more views; the second upload.", "altId": "5G7_zXwQsxY" }, { "no": "6", "title": "Negation", "id": "XAd4h870Q88", "label": "Lecture 5" }, { "no": "7", "title": "Only and some Ambiguities", "id": "dDYkUHjnKJw", "label": "Lecture 6" }, { "no": "8", "title": "Logical Equivalencies and Confinement", "id": "TibiMl7rYZc", "label": "Lecture 7" }, { "no": "9", "title": "Wrap-Up", "id": "f1o9RCzcgtA", "label": "Lecture 8" } ] }, { "kind": "l2010", "title": "Logic 2010 demos", "age": "about 8 years ago", "items": [ { "no": "10", "title": "SP Predicate Symbolization", "id": "7_NridgD8Io", "label": "Logic 2010" } ] }, { "kind": "example", "title": "Example problems", "age": "5–10 years ago", "items": [ { "no": "11", "title": "Basic Symbolizations", "id": "ZoWRGPdZP2Q", "label": "Example" }, { "no": "12", "title": "Harder Symbolizations", "id": "6sUBPoVvxlQ", "label": "Example" }, { "no": "13", "title": "Negated Quantifiers", "id": "Rqvc5FWMcMg", "label": "Example" }, { "no": "14", "title": "Test Style Questions", "id": "vIZDDytBWDY", "label": "Example" } ] } ]
  },
  { "n": 6, "topic": "Single-place predicate derivations", "groups": [ { "kind": "lecture", "title": "Lectures", "age": "about 9 years ago", "items": [ { "no": "1", "title": "Single Place Derivations in PL, part 1", "id": "2uF6WwyuT9g", "label": "Lecture" }, { "no": "2", "title": "Single Place Derivations in PL, part 2", "id": "L0YtcJTSngk", "label": "Lecture" } ] }, { "kind": "skill", "title": "Skills", "age": "about 5 years ago", "items": [ { "no": "3", "title": "Show Line Breakdown", "id": "Ove-x6_xrMk", "label": "Skill 1" }, { "no": "4", "title": "Proof Structure", "id": "Pu2k11Bqfus", "label": "Skill 2" }, { "no": "5", "title": "Capturing", "id": "vxr_8TGji4Y", "label": "Skill 3" } ] }, { "kind": "skill", "title": "Skills, earlier series", "age": "about 10 years ago", "items": [ { "no": "6", "title": "Double UD", "id": "HEdbcNPX4Aw", "label": "Skill 1" }, { "no": "7", "title": "Blind UI", "id": "joNLORjYtNk", "label": "Skill 2" }, { "no": "8", "title": "Order Matters", "id": "xIWzzVU4lZ8", "label": "Skill 3" } ] }, { "kind": "l2010", "title": "Logic 2010 demos", "age": "about 10 years ago", "items": [ { "no": "9", "title": "PL Derivations", "id": "OROAXl9ND00", "label": "Logic 2010" } ] }, { "kind": "example", "title": "Example problems", "age": "5–10 years ago", "items": [ { "no": "10", "title": "All Rules", "id": "Z3QRzh-8dnk", "label": "Example" }, { "no": "11", "title": "All Rules 2", "id": "M8M46NecJU8", "label": "Example" }, { "no": "12", "title": "Basic SP Derivation", "id": "oUFrEfh5rOk", "label": "Example" }, { "no": "13", "title": "Basic SP Derivation 2", "id": "6rmpC2W5Qpo", "label": "Example" } ] } ]
  },
  { "n": 7, "topic": "Multi-place predicate symbolization", "groups": [ { "kind": "lecture", "title": "Lectures", "age": "about 9 years ago", "items": [ { "no": "1", "title": "Multi Place Symbolization in PL, part 1", "id": "l1QX60Ij8IA", "label": "Lecture" }, { "no": "2", "title": "Multi Place Symbolization in PL, part 2", "id": "jUQhAf-4RkI", "label": "Lecture" }, { "no": "3", "title": "Multi Place Symbolization in PL, part 3", "id": "4z30LsDHGdY", "label": "Lecture" } ] }, { "kind": "example", "title": "Example problems", "age": "5–10 years ago", "items": [ { "no": "4", "title": "Basic 1", "id": "Dkl5qaGnwo8", "label": "Example" }, { "no": "5", "title": "Exclusion and Superlative", "id": "jf2I5B_xgMM", "label": "Example" }, { "no": "6", "title": "Symbolizations 1", "id": "PJ-6MvUtNIc", "label": "Example" }, { "no": "7", "title": "Symbolizations 2", "id": "t3hImlfGRP4", "label": "Example" }, { "no": "8", "title": "Symbolizations 3", "id": "vpHch_lISG4", "label": "Example" }, { "no": "9", "title": "Translations", "id": "T8weQJkLAeE", "label": "Example" } ] } ]
  },
  { "n": 8, "topic": "Multi-place predicate derivations", "groups": [ { "kind": "lecture", "title": "Lectures", "age": "about 9 years ago", "items": [ { "no": "1", "title": "Multi Place Derivations in PL", "id": "xKN3MNZhlqY", "label": "Lecture" } ] }, { "kind": "skill", "title": "Skills", "age": "about 5 years ago", "items": [ { "no": "2", "title": "EG and UD with Example", "id": "E1weRMzM08I", "label": "Skill" } ] }, { "kind": "example", "title": "Example problems", "age": "5–10 years ago", "items": [ { "no": "3", "title": "All Rules Derivation", "id": "xrUthjZyFcU", "label": "Example" }, { "no": "4", "title": "All Rules Harder", "id": "mZjXO07Rk7o", "label": "Example" }, { "no": "5", "title": "Basic Derivation", "id": "IPKT1nKipkY", "label": "Example" }, { "no": "6", "title": "Basic Derivation 2", "id": "inN_KiEZZ10", "label": "Example" }, { "no": "7", "title": "Test Level Derivations", "id": "cR6P2O6bFlI", "label": "Example" } ] } ]
  },
  { "n": 9, "topic": "Predicate semantics", "groups": [ { "kind": "lecture", "title": "Lectures", "age": "about 5 years ago", "items": [ { "no": "1", "title": "Predicate Semantics Intro", "id": "wQ6eZMdLuc4", "label": "Lecture 1" }, { "no": "2", "title": "Intensional and Extensional Interpretations", "id": "qQMRXG_zcXA", "label": "Lecture 2" }, { "no": "3", "title": "Single-Place Finite Extensional Models", "id": "abf35OSir08", "label": "Lecture 3" }, { "no": "4", "title": "Single Place Truth-Functional Expansion", "id": "OCbafT5WnJ8", "label": "Lecture 4" }, { "no": "5", "title": "Multi-Place Finite Extensional Models", "id": "AaXeebepbb4", "label": "Lecture 5" }, { "no": "6", "title": "Multi-Place Truth-Functional Expansion", "id": "RD8B0F7Muzc", "label": "Lecture 6" } ] }, { "kind": "lecture", "title": "Lectures, earlier series", "age": "about 9 years ago", "items": [ { "no": "7", "title": "Predicate Logic Semantics, part 1", "id": "FPVHgLiaWhs", "label": "Lecture" }, { "no": "8", "title": "Predicate Logic Semantics, part 2", "id": "nuGsWMXkTQM", "label": "Lecture" } ] }, { "kind": "l2010", "title": "Logic 2010 demos", "age": "about 9 years ago", "items": [ { "no": "9", "title": "Unit 9 demo", "id": "aKO7Th4nYg4", "label": "Logic 2010" } ] }, { "kind": "example", "title": "Example problems", "age": "about 5 years ago", "items": [ { "no": "10", "title": "Finite Extensional Model 1", "id": "Bl8xnPVtBIE", "label": "Example" }, { "no": "11", "title": "Finite Extensional Model 2", "id": "9SGItsKGms4", "label": "Example" }, { "no": "12", "title": "Finite Extensional Model 3", "id": "oGDzhyxMp9g", "label": "Example" }, { "no": "13", "title": "Truth-Functional Expansion 1", "id": "2x3kfHOYGWg", "label": "Example" }, { "no": "14", "title": "Truth-Functional Expansion 2", "id": "-b-gkmfDBHU", "label": "Example" } ] } ]
  }
 ]
};
