// Downloads the site's fonts (all SIL OFL) from Google Fonts into assets/fonts/ so pages never load third-party fonts.
// Run: node tools/fonts.mjs   (re-run after adding new Chinese text: the CJK font is subset to the characters used)
import fs from 'node:fs';
import path from 'node:path';

const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36';
const OUT = 'assets/fonts';
const SCAN = ['index.html', '404.html', 'weather', 'hiking', 'arrivals', 'cams', 'trips', 'savings', 'study', 'assets/js', 'partials'];

async function css(url) {
  const r = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(r.status + ' ' + url);
  return r.text();
}
async function save(url, file) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(r.status + ' ' + url);
  fs.writeFileSync(path.join(OUT, file), Buffer.from(await r.arrayBuffer()));
  console.log('saved', file);
}
// Pull every @font-face block; keep only the latin (and latin-ext) subsets to stay small.
async function family(name, query, prefix) {
  const text = await css('https://fonts.googleapis.com/css2?family=' + query + '&display=swap');
  const blocks = text.split('/*').slice(1);
  const out = [];
  for (const b of blocks) {
    const subset = b.slice(0, b.indexOf('*/')).trim();
    if (subset !== 'latin' && subset !== 'latin-ext') continue;
    const url = /url\((https:[^)]+\.woff2)\)/.exec(b)[1];
    const weight = /font-weight:\s*([^;]+);/.exec(b)[1].trim();
    const range = /unicode-range:\s*([^;]+);/.exec(b)[1].trim();
    const file = `${prefix}-${subset}.woff2`;
    await save(url, file);
    out.push(`@font-face{font-family:"${name}";font-style:normal;font-weight:${weight};font-display:swap;src:url(../fonts/${file}) format("woff2");unicode-range:${range}}`);
  }
  return out;
}
function usedChinese() {
  const set = new Set();
  const walk = p => {
    if (!fs.existsSync(p)) return;
    if (fs.statSync(p).isDirectory()) { for (const f of fs.readdirSync(p)) if (f !== 'vendor' && f !== 'data') walk(path.join(p, f)); return; }
    if (!/\.(html|js|css)$/.test(p)) return;
    for (const ch of fs.readFileSync(p, 'utf8')) if (/[㐀-鿿＀-￯　-〿]/.test(ch)) set.add(ch);
  };
  SCAN.forEach(walk);
  return [...set].sort().join('');
}
async function cjk() {
  const chars = usedChinese();
  if (!chars) { console.log('no Chinese text yet; skipping WenKai'); return []; }
  const text = await css('https://fonts.googleapis.com/css2?family=LXGW+WenKai+TC&display=swap&text=' + encodeURIComponent(chars));
  const m = /url\((https:[^)]+)\) format\('woff2'\)/.exec(text);
  if (!m) throw new Error('WenKai: no woff2 in response');
  await save(m[1], 'wenkai-tc-subset.woff2');
  console.log(`WenKai subset: ${[...chars].length} characters`);
  return ['@font-face{font-family:"LXGW WenKai TC";font-style:normal;font-weight:400;font-display:swap;src:url(../fonts/wenkai-tc-subset.woff2) format("woff2")}'];
}

fs.mkdirSync(OUT, { recursive: true });
const faces = [
  ...(await family('Bricolage Grotesque', 'Bricolage+Grotesque:opsz,wght@12..96,200..800', 'bricolage')),
  ...(await family('Martian Mono', 'Martian+Mono:wght@300..600', 'martian-mono')),
  ...(await cjk()),
];
fs.mkdirSync('assets/css', { recursive: true });
fs.writeFileSync('assets/css/fonts.css', '/* generated by tools/fonts.mjs */\n' + faces.join('\n') + '\n');
console.log('wrote assets/css/fonts.css');
